ENGINE_VERSION = "1.1.0"
SCHEMA_VERSION = "operation-v0.1.0"
CONTEXT_VERSION = "context-v0.2.0"
SAFETY_VERSION = "safety-v0.2.0"
EXPLICIT_RULES_VERSION = "explicit-v0.4.0"
PARSER_VERSION = (
    f"rules-v0.1.0+{EXPLICIT_RULES_VERSION}+{CONTEXT_VERSION}+{SAFETY_VERSION}"
)
